### ISSUE TITLE
Mobile iOS app switch does not stay on

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey-issues-dp#111]
I use switches from the virtual devices app, in the old app they stayed on if I switched to on, in the new app it Goes on and directly off.

**Comment by jeroenbos22** [comment]
Also When switched I can not switch it the other way around. For example if switched on it Goes on but the switch is showing off. Tapping it again it again tries to switch on (What it already was). This also happens the other way around. So if you tap it 10 times in a round it Goes 10x on or 10x off instead off toggeling. Only way to correct it is full app restart.

**Comment by joachimroeleveld** [comment]
What happens if you try this in the desktop interface and reload the page after you click a toggle? Does it stay on?

**Comment by joachimroeleveld** [comment]
The current mobile app doesn't handle errors properly which is why it "works" in the current mobile app (it doesn't update its state). However, in the Preview version, the switch toggles back because an error is thrown in addressing the device. This should therefore probably be addressed in the virtual devices app.
