### ISSUE TITLE
Stopcontact dimmen on personal flow (voice command)

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey-issues-dp#16]
**What is your Homey version (Settings → System)?**

1.2.0 RC 9

**What did you try to achieve?**

I have this flow. 

**What was the result?**

When I say "radio volume omhoog" it works but Homey also responds with "Ik kon geen stopcontacten vinden om te dimmen"

**What did you expect as result?**

Homey quiet

**Any other remarks**

![flow](https://cloud.githubusercontent.com/assets/2961896/24329310/d98342cc-1202-11e7-91e0-ed2eada83d2e.png)

**Comment by Tweake** [comment]
When I say "radio volume omhoog" homey responds with "Het spijt me, maar ik begrijp niet wat je bedoelt", no stopcontacten are mentioned here. 

The message ("I'm sorry, but I am not sure what you would like me to do" in English) has been added because many people have asked for feedback when Homey did not trigger any Flows, apps or system functionality.

The reason you are getting this message despite your Flow is that you are using Logic condition cards to check the speech input. This makes it impossible to verify whether a flow was triggered, so Homey assumes the flow was not triggered to be on the safe side.

The solution is to use the speech input card "Something was said containing". For more info about that card, please see: https://github.com/athombv/homey/issues/1426
