### ISSUE TITLE
Zigbee documentation: add RAW data to the tree or add link to translation table

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-issues-dp#52]
Currently on developers.athom.com the ZigBee Cluster Documentation consists of:
- a link to the ZigBee Cluster Specification (PDF)
- the tree of readable cluster names with corresponding attributes and commands

Similar to Z-wave, this last tree is a translation which can hold errors.
In addition, to resolve inconsistencies, it would help developers to be able to use the RAW data of the clusters, attributes and commands used for other home automation platform (less elegant == still using RAW data) for setting up the drivers / app for Zigbee devices...

Currently, I use information at https://github.com/zigbeer/zcl-id/ but I would prefer to use the same translation table as Athom used; is it possible to add it to the developers.athom.com site? 
Again similar to Z-wave....

**Comment by TedTolboom** [comment]
So since you forked the zigbeer zcl-id; [An utility for getting ZCL identifiers defined by ZigBee Cluster Library.](https://github.com/athombv/zcl-id) 
I guess that could be the link / answer to this question...

**Comment by jeroenvollenbrock** [comment]
The list on https://apps.developer.athom.com/tutorial-ZigBee-Clusters%20Reference.html is actually not a translation, but just a view for the zcl-id repo which is also being used internally by the zigbee stack. Unfortunately, zigbee does not support communicating raw data due to the subscribe structure it uses, so that is not a possibility for now. It might be possible to extend the lower level stack to enable promiscious mode, but that will cause a performance hit. I'm closing this issue for now, but feel free to submit a feature request in the regular issue tracker.
