### ISSUE TITLE
zwave problems in 1.2.0

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#9]
**What is your Homey version (Settings → System)?**

1.2.0 rc6

**What did you try to achieve?**

I have zwave problems in RC6. For a number of days already my zwave is not very responsive. Some commands just do not get executed by the zwave device.  *Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

crash report after a zwave device did not get triggered correctly: B7163DB995

**Comment by jaxc0402** [comment]
I have the same issue, but not continusly

**Comment by jeroenvollenbrock** [comment]
Can you post a zwave log of a period in which these issues occur?

**Comment by gruijter** [comment]
Now all of my zwave crashed: 8DEE20A5D8

**Comment by mruiter** [comment]
Same here, ending up in lockup every 24 to 48 hours. Seems to be the same mem low queue errors and build up that has been there since 1.0.4 and only got pushed back a bit.
People on 1.1.9 and with 45+ devices are also reporting this including the lockups and memfull on slack general.

**Comment by WeeJeWel** [comment]
Please explain what a 'lockup' means in observable terms :-) It's really hard for us when these 'community definitions' are being used, haha.

**Comment by mruiter** [comment]
Same as i had before.
Lockups ala losing cloud connection and Downsyndrhomey stutter like hell with z-wave non repsonsive on triggers
Lockups where stutter and z-wave really slow with a log full of queue errors and mem going up to the sky . yesterday after a 21 hour run since last reboot it was slow when comming home. no response triggers. Opend homey app on Phone no repsonse on flips for switches. Then started chrome to go to my.athom.com but no cloud connection.
Tried local IP just loaded the main menu and then lost wifi connection . It was not pingable anymore on local ip. So a PTP brought it back to live

**Comment by mruiter** [comment]
To me it still looks like the same processdata and queue bug. Now that media takes some more memory i guess it shows up again filling the swap to offload the queue. I think theres also a github issue where jeroen mentioned a "Isn't this the slow and delayed secure z-wave connections we see". This would also be a problem with 45 devices offcourse and building up queue

**Comment by WeeJeWel** [comment]
Alright, thanks! I don't think it's Z-Wave specific then, but simply Homey being too slow to handle the traffic. In the next release we've prioritized secure Z-Wave messages, let me know how that behaves.

**Comment by mruiter** [comment]
Great ! Cant wait to test. Guess i at least can tell within 24 to 48 hours if it got better :)

**Comment by jeroenvollenbrock** [comment]
@mruiter Did it get better?

**Comment by mruiter** [comment]
Yes, it indeed got much better . I havnt seen any major errors for the last 48 hours
